name: Automated Testing for python files

on:
  pull_request:
    branches: [test]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Additional dependencies
        run: pip install flask pytest

      - name: Run tests
        run: pytest test.py
